// SF Matcha shops from the sourced San Francisco matcha research dataset.
// x/y are percentages within the stylized SF map (0-100).
// status: 'confirmed' | 'reported' | 'none' | 'call' | 'closed'

const SHOPS = [
  {
    id: "asha-tea-house",
    name: "Asha Tea House",
    address: "17 Kearny St",
    hood: "FiDi / Union Square",
    status: "confirmed",
    topPick: true,
    buzzy: false,
    emoji: "🫖",
    note: "Reliable downtown matcha anchor with a dedicated Matcha Latte with Soy Milk.",
    soyNote: "Soy milk is available for the Matcha Latte; the menu specifically lists Pacific Foods Soy.",
    source: "https://asha-tea-house.grubbio.com/menu",
    lat: 37.7881702, lng: -122.4037073,
    x: 58.7, y: 37.8,
    price: "$$",
    hours: "Mon–Fri 10am–6:30pm; Sat 10:30am–6:30pm; Sun closed",
  },
  {
    id: "maruwu-seicha",
    name: "Maruwu Seicha",
    address: "1737 Post St #368",
    hood: "Japantown",
    status: "confirmed",
    topPick: true,
    buzzy: false,
    emoji: "🎋",
    note: "Award-style Japanese matcha, soft serve, tarts, and customizable lattes.",
    soyNote: "Soy milk is available for matcha and hojicha lattes, alongside whole, oat, and almond milk.",
    source: "https://www.doordash.com/business/maruwu-seicha-14102333/menu",
    lat: 37.7851991, lng: -122.4303062,
    x: 47.7, y: 39.4,
    price: "$$",
    hours: "Sun–Thu 11am–9pm; Fri–Sat 11am–9:30pm",
  },
  {
    id: "cere-tea",
    name: "Ceré Tea",
    address: "1186 Valencia St",
    hood: "Mission",
    status: "confirmed",
    topPick: true,
    buzzy: true,
    emoji: "🍵",
    note: "New SF location with matcha and hojicha einspanners, fruit matcha, and strong delivery ratings.",
    soyNote: "Soy milk is available for matcha drinks.",
    source: "https://postmates.com/store/cere-tea/GDbcB8o0WkKVXAiXEwc4mA/c9fa33fc-d479-5b61-8f0c-78b78ba90a4a/0367e151-2460-578d-b321-08c9954a3b33/6019a96f-5668-5fd9-ba98-f52e6a4cf54e",
    lat: 37.7539712, lng: -122.4210238,
    x: 51.5, y: 56.3,
    price: "$$",
    hours: "daily 10am–7pm",
  },
  {
    id: "oishii-matcha",
    name: "Oishii Matcha",
    address: "2299 Market St Suite A",
    hood: "Castro",
    status: "confirmed",
    topPick: true,
    buzzy: false,
    emoji: "💚",
    note: "Ceremonial-grade matcha cafe known for bitter, grassy lattes and yuzu matcha soda.",
    soyNote: "A Matcha Mango Latte with soy milk is listed.",
    source: "https://www.restaurantji.com/ca/san-francisco/oishii-matcha-/",
    lat: 37.7640737, lng: -122.4328131,
    x: 46.7, y: 50.8,
    price: "$$",
    hours: "daily 11am–8:30pm",
  },
  {
    id: "kiss-of-matcha-clement",
    name: "Kiss of Matcha - Clement",
    address: "750 Clement St",
    hood: "Inner Richmond",
    status: "confirmed",
    topPick: true,
    buzzy: false,
    emoji: "💋",
    note: "One of SF's favorite soft-serve-and-latte matcha stops, known for its Uji latte. The Matcha Cloud foam contains whole milk and cream.",
    soyNote: "Soy milk is available for lattes. The Matcha Cloud foam contains whole milk and cream, so choose a standard matcha latte for a soy-based drink.",
    source: "https://kiss-of-matcha.res-menu.net/menu",
    lat: 37.7829348, lng: -122.4674571,
    x: 32.4, y: 40.6,
    price: "$$",
    hours: "Mon closed; Tue–Thu 10am–8pm; Fri–Sat 10am–10pm; Sun 10am–8pm",
  },
  {
    id: "kiss-of-matcha-broadway",
    name: "Kiss of Matcha - Broadway",
    address: "612 Broadway",
    hood: "North Beach / Chinatown",
    status: "confirmed",
    topPick: true,
    buzzy: false,
    emoji: "💋",
    note: "Second central location for the same matcha latte and dessert menu. The Matcha Cloud foam contains whole milk and cream.",
    soyNote: "Soy milk is available for lattes. The Matcha Cloud foam contains whole milk and cream, so choose a standard matcha latte for a soy-based drink.",
    source: "https://kiss-of-matcha.res-menu.net/menu",
    lat: 37.797946, lng: -122.407346,
    x: 57.2, y: 32.5,
    price: "$$",
    hours: "Mon closed; Tue–Thu 10am–8pm; Fri–Sun 10am–9pm",
  },
  {
    id: "kiss-of-matcha-irving",
    name: "Kiss of Matcha - Irving",
    address: "2127 Irving St",
    hood: "Inner Sunset",
    status: "confirmed",
    topPick: true,
    buzzy: true,
    emoji: "💋",
    note: "Westside location from a known matcha dessert chain and a useful Golden Gate Park stop. The Matcha Cloud foam contains whole milk and cream.",
    soyNote: "Soy milk is available for lattes. The Matcha Cloud foam contains whole milk and cream, so choose a standard matcha latte for a soy-based drink.",
    source: "https://kiss-of-matcha.res-menu.net/menu",
    lat: 37.7631891, lng: -122.4808579,
    x: 26.9, y: 51.3,
    price: "$$",
    hours: "Sun–Thu 11am–8pm; Fri–Sat 11am–10pm",
  },
  {
    id: "matcha-cafe-maiko-japantown",
    name: "Matcha Cafe Maiko - Japantown",
    address: "1581 Webster St #175",
    hood: "Japantown",
    status: "confirmed",
    topPick: true,
    buzzy: false,
    emoji: "🍦",
    note: "Dedicated matcha dessert cafe with lattes, floats, soft serve, parfaits, and powders.",
    soyNote: "Soy milk is available for matcha drinks, alongside whole and almond milk.",
    source: "https://www.doordash.com/store/675964/",
    lat: 37.7849544, lng: -122.4317274,
    x: 47.1, y: 39.5,
    price: "$$",
    hours: "Sun–Thu 11am–9pm; Fri–Sat 11am–10pm",
  },
  {
    id: "matcha-cafe-maiko-stonestown",
    name: "Matcha Cafe Maiko - Stonestown",
    address: "3251 20th Ave Ste 250K",
    hood: "Stonestown",
    status: "confirmed",
    topPick: true,
    buzzy: false,
    emoji: "🍦",
    note: "Dedicated matcha chain location near SFSU/Stonestown.",
    soyNote: "Soy milk is available for lattes and frappes, alongside whole and almond milk.",
    source: "https://www.doordash.com/store/675964/",
    lat: 37.7277726, lng: -122.4768761,
    x: 28.5, y: 70.4,
    price: "$$",
    hours: "Mon–Sat 10am–9pm; Sun 11am–6pm",
  },
  {
    id: "matcha-cafe-maiko-chinatown",
    name: "Matcha Cafe Maiko - Chinatown",
    address: "756 Grant Ave",
    hood: "Chinatown",
    status: "confirmed",
    topPick: true,
    buzzy: false,
    emoji: "🍦",
    note: "Central dedicated matcha chain location with lattes and desserts.",
    soyNote: "Soy milk is available for lattes and frappes, alongside whole and almond milk.",
    source: "https://www.doordash.com/store/675964/",
    lat: 37.7942158, lng: -122.4062082,
    x: 57.7, y: 34.5,
    price: "$$",
    hours: "Mon–Fri 12pm–7pm; Sat–Sun 11am–7pm",
  },
  {
    id: "il-parco",
    name: "Il Parco",
    address: "215 Lincoln Blvd",
    hood: "Presidio",
    status: "confirmed",
    topPick: false,
    buzzy: false,
    emoji: "🌲",
    note: "Presidio cafe serving a matcha latte with a soy milk option.",
    soyNote: "Soy milk is available for the matcha latte.",
    source: "https://ilparcosf.com/menu/cafe",
    lat: 37.8018663, lng: -122.4562556,
    x: 37, y: 30.4,
    price: "$",
    hours: "daily 8am–8pm",
  },
  {
    id: "fueling-station-cafe",
    name: "Fueling Station Cafe",
    address: "2436 Polk St",
    hood: "Russian Hill",
    status: "reported",
    topPick: false,
    buzzy: false,
    emoji: "⛽",
    note: "Neighborhood cafe with an official organic ceremonial-grade matcha latte.",
    soyNote: "Soy milk has been reported available for the matcha latte.",
    source: "https://fueling-station-cafe.square.site/",
    lat: 37.7993092, lng: -122.4223102,
    x: 51, y: 31.8,
    price: "$",
    hours: "Mon–Sat 7am–4pm; Sun 7am–3pm",
  },
  {
    id: "lulu-fresh",
    name: "Lulu Fresh",
    address: "50 Francisco St Suite 105",
    hood: "North Beach / Embarcadero",
    status: "confirmed",
    topPick: false,
    buzzy: false,
    emoji: "🥤",
    note: "Healthy cafe/grocery stop with a matcha latte product page.",
    soyNote: "Soy milk is available for the matcha latte.",
    source: "https://www.lulufresh.co/products/matcha-latte",
    lat: 37.8060896, lng: -122.4061407,
    x: 57.7, y: 28.1,
    price: "$",
    hours: "Mon–Fri 7am–4pm; Sat 8am–4pm; Sun closed",
  },
  {
    id: "sutter-street-cafe",
    name: "Sutter Street Cafe",
    address: "450 Sutter St #7",
    hood: "Union Square",
    status: "confirmed",
    topPick: false,
    buzzy: false,
    emoji: "🏙️",
    note: "Basic downtown workday matcha option.",
    soyNote: "Soy milk is listed for the organic matcha latte.",
    source: "https://www.allmenus.com/ca/san-francisco/378888-sutter-st-cafe/menu/",
    lat: 37.7896524, lng: -122.4079043,
    x: 57, y: 37,
    price: "$",
    hours: "Mon–Fri 8am–4pm; Sat–Sun closed",
  },
  {
    id: "home-coffee-roasters-grant",
    name: "Home Coffee Roasters - Grant",
    address: "455 Grant Ave",
    hood: "Chinatown / FiDi",
    status: "confirmed",
    topPick: false,
    buzzy: false,
    emoji: "🏠",
    note: "Reliable local cafe chain with a customizable matcha latte.",
    soyNote: "Soy milk is available for the Matcha Latte.",
    source: "https://homecoffeeroastersclement.toast.site/menu/home-coffee-roasters-grant-455-grant-ave/group_06397405-debe-44c6-a376-1aec23c35a5f/item-matcha-latte_fdbebd5c-dbcf-4f16-84ae-38b2bbcfef90",
    lat: 37.7912579, lng: -122.4058748,
    x: 57.8, y: 36.1,
    price: "$",
    hours: "Mon–Fri 7:30am–3:30pm; Sat–Sun 8am–3:30pm",
  },
  {
    id: "steep-creamery-and-tea",
    name: "Steep Creamery & Tea",
    address: "270 Brannan St",
    hood: "South Beach",
    status: "closed",
    topPick: false,
    buzzy: false,
    emoji: "🍨",
    note: "Matcha and tea spot that Google Maps marks temporarily closed.",
    soyNote: "Soy milk is listed for the matcha tea latte.",
    source: "https://places.singleplatform.com/steep-creamery--tea/menu",
    lat: 37.7826306, lng: -122.3913361,
    x: 63.8, y: 40.8,
    price: "$",
    hours: "Temporarily closed",
  },
  {
    id: "dolores-park-cafe",
    name: "Dolores Park Cafe",
    address: "501 Dolores St",
    hood: "Mission Dolores",
    status: "confirmed",
    topPick: false,
    buzzy: false,
    emoji: "🌞",
    note: "Park-adjacent cafe serving matcha drinks with a soy milk option.",
    soyNote: "Soy milk is available as a substitution.",
    source: "https://parkcafelife.com/wp-content/uploads/2025/03/Dolores_HandHeldMenu-2025-03-18.pdf",
    lat: 37.7613386, lng: -122.4257977,
    x: 49.6, y: 52.3,
    price: "$",
    hours: "Mon–Sat 7:30am–5pm; Sun 8am–5pm",
  },
  {
    id: "excelsior-coffee-xlcr",
    name: "Excelsior Coffee / XLCR",
    address: "4495 Mission St",
    hood: "Excelsior",
    status: "confirmed",
    topPick: false,
    buzzy: false,
    emoji: "⚡",
    note: "Strong neighborhood coffee option with a matcha tea latte.",
    soyNote: "Soy milk is available as an add-on.",
    source: "https://www.xlcrsf.com/menu",
    lat: 37.7263543, lng: -122.4333723,
    x: 46.4, y: 71.2,
    price: "$",
    hours: "daily 7:30am–4pm",
  },
  {
    id: "blue-house-cafe",
    name: "Blue House Cafe",
    address: "302 Randolph St",
    hood: "Ingleside",
    status: "confirmed",
    topPick: false,
    buzzy: false,
    emoji: "🏡",
    note: "Neighborhood cafe with banana coffee and matcha drinks.",
    soyNote: "Soy milk is listed as a matcha latte alternative.",
    source: "https://menuwithpricesonline.com/blue-house-cafe-menu/ca/san-francisco/45576/",
    lat: 37.7144818, lng: -122.4655812,
    x: 33.2, y: 77.6,
    price: "$",
    hours: "daily 7:30am–5pm",
  },
  {
    id: "best-boy-electric",
    name: "Best Boy Electric",
    address: "1746 Post St",
    hood: "Japantown",
    status: "reported",
    topPick: true,
    buzzy: true,
    emoji: "⚡",
    note: "Hand-whisked matcha inside New People, including a minimalist matcha latte and black sesame matcha.",
    soyNote: "Soy milk has been reported available, but the ordering menu does not show every milk option.",
    source: "https://best-boy-electric.square.site/",
    lat: 37.7856787, lng: -122.4305775,
    x: 47.6, y: 39.1,
    price: "$$",
    hours: "Mon–Fri 9am–4pm; Sat–Sun 10am–5pm",
  },
  {
    id: "junbi-matcha-and-tea",
    name: "Junbi Matcha & Tea",
    address: "685 Market St #130",
    hood: "SoMa / FiDi",
    status: "confirmed",
    topPick: true,
    buzzy: true,
    emoji: "🧋",
    note: "National matcha chain's SF location; strong fruit matcha, cold brew matcha, and boba-ish options.",
    soyNote: "Unsweetened soy milk is available.",
    source: "https://joe.coffee/locations/ca/san-francisco/junbi-matcha-and-tea-san-francisco-san-francisco-45c9022d-62e4-46d3-8449-edc63a7df87e/",
    lat: 37.7877269, lng: -122.4026141,
    x: 59.1, y: 38,
    price: "$$",
    hours: "Mon–Fri 8:30am–5pm; Sat–Sun 10am–5pm",
  },
  {
    id: "stonemill-matcha",
    name: "Stonemill Matcha",
    address: "561 Valencia St",
    hood: "Mission",
    status: "none",
    topPick: true,
    buzzy: false,
    emoji: "🪨",
    note: "The SF matcha classic: rose, ginger, hand-whisked matcha, matchacano, and Japanese cafe food.",
    soyNote: "Soy is not listed; oat milk is the menu's substitute.",
    source: "https://www.stonemillmatcha-us.com/menu",
    lat: 37.7639681, lng: -122.4216256,
    x: 51.3, y: 50.9,
    price: "$$",
    hours: "Mon–Fri 10am–4pm; Sat–Sun 9am–7pm",
  },
  {
    id: "shoji",
    name: "Shoji",
    address: "140 New Montgomery St Suite 1",
    hood: "SoMa / FiDi",
    status: "call",
    topPick: true,
    buzzy: true,
    emoji: "✨",
    note: "Buzzy matcha einspanner destination; cafe by day, bar/restaurant later.",
    soyNote: "Soy availability is not listed; oat milk has been reported available.",
    source: "https://www.theshojisf.com/faq",
    lat: 37.7866713, lng: -122.399674,
    x: 60.4, y: 38.6,
    price: "$$",
    hours: "Mon–Fri 8am–2:30pm; Sat–Sun 9am–2:30pm",
  },
  {
    id: "nagomi",
    name: "Nagomi",
    address: "74 New Montgomery St",
    hood: "SoMa / FiDi",
    status: "call",
    topPick: true,
    buzzy: true,
    emoji: "🌿",
    note: "Newer Shizuoka-focused cafe with ultra-premium matcha and soft serve.",
    soyNote: "Soy availability is not listed; oat milk is available with no upcharge.",
    source: "https://cafenagomi.com/",
    lat: 37.787672, lng: -122.4009555,
    x: 59.8, y: 38.1,
    price: "$$",
    hours: "Mon–Sat 10:30am–5pm; Sun closed",
  },
  {
    id: "tadaima-mission",
    name: "Tadaima - Mission",
    address: "3515 20th St B",
    hood: "Mission",
    status: "none",
    topPick: true,
    buzzy: true,
    emoji: "🍙",
    note: "Buzzy Japanese sando/onigiri/matcha cafe with ceremonial-grade matcha drinks.",
    soyNote: "Soy is not listed; oat and almond milk are available.",
    source: "https://tadaimasf.com/san-francisco-suite-b-tadaima-sf-drink-menu",
    lat: 37.7584516, lng: -122.4195436,
    x: 52.2, y: 53.8,
    price: "$$",
    hours: "Mon–Thu 11am–4:30pm; Fri–Sun 10am–5:30pm",
  },
  {
    id: "tadaima-marina",
    name: "Tadaima - Marina",
    address: "1849 Union St",
    hood: "Cow Hollow / Marina",
    status: "none",
    topPick: true,
    buzzy: true,
    emoji: "🍙",
    note: "Cow Hollow location of Tadaima's matcha/sando concept.",
    soyNote: "Soy is not listed; oat milk is available.",
    source: "https://www.toasttab.com/local/order/tadaima-marina/item-straight-matcha_c87c2662-0b5c-4a06-98ef-42c8a1a543a6",
    lat: 37.7976647, lng: -122.4297214,
    x: 48, y: 32.7,
    price: "$$",
    hours: "Mon–Thu 11am–5:30pm; Fri–Sun 10:30am–5:30pm",
  },
  {
    id: "tadaima-inner-sunset",
    name: "Tadaima - Inner Sunset",
    address: "1248 9th Ave",
    hood: "Inner Sunset",
    status: "none",
    topPick: true,
    buzzy: true,
    emoji: "🍙",
    note: "New third Tadaima location near Golden Gate Park.",
    soyNote: "Soy is not listed; oat and almond milk are available.",
    source: "https://missionlocal.org/2025/12/sf-sunset-buzz-december/",
    lat: 37.7650291, lng: -122.4661625,
    x: 32.9, y: 50.3,
    price: "$$",
    hours: "daily 11am–5:30pm",
  },
  {
    id: "the-wild-fox",
    name: "The Wild Fox",
    address: "123 Battery St",
    hood: "FiDi",
    status: "none",
    topPick: false,
    buzzy: true,
    emoji: "🦊",
    note: "Vacant to Vibrant Japanese cafe from the SPRO team; try the Matcha Mango Shizuku if you want the novelty order.",
    soyNote: "Soy is not listed; whole milk and oat milk have been offered.",
    source: "https://48hills.org/2025/12/good-taste-a-wily-peek-at-new-japanese-cafe-wild-fox/",
    lat: 37.7927162, lng: -122.4000828,
    x: 60.2, y: 35.3,
    price: "$",
    hours: "Mon–Fri 7am–5pm; Sat–Sun 8am–2pm",
  },
  {
    id: "marigold-cafe",
    name: "Marigold Cafe",
    address: "2681 21st St",
    hood: "Mission",
    status: "none",
    topPick: true,
    buzzy: false,
    emoji: "🌼",
    note: "Tiny flower-shop cafe serving a floral lavender matcha.",
    soyNote: "Soy is not listed; oat milk is available as an add-on.",
    source: "https://marigoldsf.com/pages/cafe",
    lat: 37.757563, lng: -122.409059,
    x: 56.5, y: 54.3,
    price: "$$",
    hours: "daily 8am–3pm",
  },
  {
    id: "paper-son-coffee-fidi",
    name: "Paper Son Coffee - FiDi",
    address: "303 2nd St N102",
    hood: "East Cut / FiDi",
    status: "none",
    topPick: true,
    buzzy: false,
    emoji: "📄",
    note: "Asian American coffee favorite with strong, umami matcha latte and matcha passionfruit soda.",
    soyNote: "Soy is not listed; oat, almond, and lactose-free whole milk are available.",
    source: "https://papersoncoffee.com/menu",
    lat: 37.7856195, lng: -122.3963797,
    x: 61.7, y: 39.2,
    price: "$$",
    hours: "Mon–Fri 8am–3:30pm; Sat–Sun closed",
  },
  {
    id: "paper-son-coffee-dogpatch",
    name: "Paper Son Coffee - Dogpatch",
    address: "2343 3rd St Unit 100",
    hood: "Dogpatch",
    status: "none",
    topPick: true,
    buzzy: false,
    emoji: "📄",
    note: "Dogpatch residency at Neighbor Bakehouse; useful pastry-plus-matcha stop.",
    soyNote: "Soy is not listed; oat, almond, and lactose-free whole milk are available.",
    source: "https://papersoncoffee.com/menu",
    lat: 37.7596427, lng: -122.3881812,
    x: 65.1, y: 53.2,
    price: "$$",
    hours: "Mon–Tue closed; Wed–Sun 8am–2pm",
  },
  {
    id: "third-wheel-coffee",
    name: "Third Wheel Coffee",
    address: "991 Oak St",
    hood: "NoPa / Lower Haight",
    status: "none",
    topPick: true,
    buzzy: true,
    emoji: "🚲",
    note: "Former Lucinda's pop-up now in its own Oak Street space, with espresso drinks, matcha lattes, housemade syrups, and seasonal matcha specials.",
    soyNote: "Soy is not listed; oat, almond, and whole milk are available for the matcha latte.",
    source: "https://www.theinfatuation.com/san-francisco/reviews/third-wheel",
    lat: 37.7733139, lng: -122.4355474,
    x: 45.5, y: 45.9,
    price: "$$",
    hours: "Daily 7am–3pm",
  },
  {
    id: "black-bird-bookstore-and-cafe",
    name: "Black Bird Bookstore and Cafe",
    address: "4541 Irving St",
    hood: "Outer Sunset",
    status: "call",
    topPick: true,
    buzzy: false,
    emoji: "📚",
    note: "Bookstore cafe near Ocean Beach serving Rocky's Matcha drinks.",
    soyNote: "Soy availability is not listed; Minor Figures oat milk is available.",
    source: "https://sfstandard.com/2025/04/19/best-restaurants-sunset-dunes/",
    lat: 37.7620739, lng: -122.5067779,
    x: 16.2, y: 51.9,
    price: "$$",
    hours: "daily 7am–6pm",
  },
  {
    id: "outset-coffee-financial-district",
    name: "Outset Coffee - Financial District",
    address: "90 New Montgomery St",
    hood: "FiDi",
    status: "call",
    topPick: true,
    buzzy: false,
    emoji: "☀️",
    note: "Creative coffee shop serving dirty matcha and a vegan matcha cloud.",
    soyNote: "Soy is listed for a coffee mocktail, but its availability for matcha is unclear.",
    source: "https://zerocater.com/catering/california/san-francisco/outset-coffee/",
    lat: 37.787522, lng: -122.4008166,
    x: 59.9, y: 38.1,
    price: "$$",
    hours: "Mon–Fri 7am–5pm; Sat–Sun 9am–4pm",
  },
  {
    id: "motoring-coffee",
    name: "Motoring Coffee",
    address: "1525 Union St",
    hood: "Cow Hollow",
    status: "call",
    topPick: false,
    buzzy: true,
    emoji: "🏁",
    note: "Car-themed cafe with creative matcha drinks and no alt-milk upcharge.",
    soyNote: "Soy availability is not listed; oat and almond milk are available.",
    source: "https://www.theinfatuation.com/san-francisco/reviews/motoring-coffee",
    lat: 37.7983069, lng: -122.4246085,
    x: 50.1, y: 32.3,
    price: "$",
    hours: "daily 7am–6pm",
  },
  {
    id: "q-specialty-coffee",
    name: "Q Specialty Coffee",
    address: "3490 California St",
    hood: "Laurel Heights",
    status: "confirmed",
    topPick: false,
    buzzy: true,
    emoji: "💎",
    note: "Coffee roastery known for matcha cloud drinks and frequent lines.",
    soyNote: "Soy milk is available.",
    source: "https://www.qspecialtycoffee.com/menu",
    lat: 37.7868563, lng: -122.4515284,
    x: 39, y: 38.5,
    price: "$",
    hours: "daily 7am–5:30pm",
  },
  {
    id: "neighbor-s-corner",
    name: "Neighbor's Corner",
    address: "499 Douglass St",
    hood: "Eureka Valley / Castro",
    status: "call",
    topPick: true,
    buzzy: false,
    emoji: "🏘️",
    note: "Under-the-radar matcha haven with shots, cappuccinos, lattes, tonics, and strawberry matcha.",
    soyNote: "Soy availability is not listed on the menu.",
    source: "https://neighbors-corner.restaurants-world.net/menu",
    lat: 37.7555735, lng: -122.4387557,
    x: 44.2, y: 55.4,
    price: "$$",
    hours: "Mon–Fri 7am–3pm; Sat–Sun 8am–3pm",
  },
  {
    id: "komeya-no-bento",
    name: "Komeya No Bento",
    address: "3137 Laguna St",
    hood: "Cow Hollow / Marina",
    status: "call",
    topPick: true,
    buzzy: false,
    emoji: "🍱",
    note: "Bento spot with a serious matcha following; strawberry/mango fresh milk with matcha foam are popular.",
    soyNote: "Soy availability is not listed; oat milk is available.",
    source: "https://www.doordash.com/store/komeya-no-bento-san-francisco-28048141",
    lat: 37.8000776, lng: -122.4314107,
    x: 47.3, y: 31.4,
    price: "$$",
    hours: "Mon and Sun closed; Tue–Sat 11am–2:30pm and 5pm–6:30pm",
  },
  {
    id: "origin-lab-coffee-and-matcha",
    name: "Origin Lab Coffee & Matcha",
    address: "211 Sutter St",
    hood: "Union Square / FiDi",
    status: "confirmed",
    topPick: false,
    buzzy: true,
    emoji: "🧪",
    note: "Established in 2025, with premium ceremonial-grade matcha and Matcha Cloud drinks.",
    soyNote: "Soy milk is available.",
    source: "https://originlabcoffee.com/",
    lat: 37.7896787, lng: -122.404049,
    x: 58.6, y: 37,
    price: "$",
    hours: "daily 6am–8pm",
  },
  {
    id: "kissaten-hifi",
    name: "Kissaten HiFi",
    address: "189 6th Ave",
    hood: "Inner Richmond",
    status: "call",
    topPick: true,
    buzzy: true,
    emoji: "🎵",
    note: "Vinyl-spinning Japanese-Filipino cafe opened March 2026; matcha from Fukuoka and Uji farms, housemade syrups, matcha einspanner, and an Ichigo Matcha with strawberry purée. Their housemade banana milk uses soy milk as a base ingredient.",
    soyNote: "Soy availability as a matcha substitute is not listed; the housemade banana milk contains soy.",
    source: "https://www.theinfatuation.com/san-francisco/reviews/kissaten-hifi",
    lat: 37.7852405, lng: -122.4647832,
    x: 33.5, y: 39.4,
    price: "$$",
    hours: "Daily 8am–5pm",
  },
  {
    id: "four-chairs",
    name: "Four Chairs SF",
    address: "3282 Mission St",
    hood: "Bernal / Mission",
    status: "none",
    topPick: false,
    buzzy: true,
    emoji: "🪑",
    note: "Brunch spot with photogenic matcha drinks, including strawberry, mango, and Matcha Coconut Cloud options.",
    soyNote: "Soy is not listed; whole milk, Oatly, and almond milk are available.",
    source: "https://www.fourchairssf.com/_files/ugd/84dca7_1ddb14cf73d649339a46b81e3c2a91db.pdf",
    lat: 37.7444324, lng: -122.4209514,
    x: 52.1, y: 62.5,
    price: "$$",
    hours: "Mon–Fri 10am–2:30pm; Sat–Sun 9am–3pm",
  },
  {
    id: "bageletto-sf",
    name: "Bageletto SF",
    address: "76 14th St",
    hood: "Mission / SoMa",
    status: "none",
    topPick: false,
    buzzy: true,
    emoji: "🥯",
    note: "Bagel shop serving a Coconut Cloud Matcha and classic matcha latte.",
    soyNote: "Soy is not listed; oat milk is the non-dairy option for the Coconut Cloud Matcha.",
    source: "https://www.toasttab.com/local/order/bageletto-14th/item-coconut-cloud-matcha_abf996bf-b849-4090-af66-3cd16a8dc0d1",
    lat: 37.7688351, lng: -122.4150418,
    x: 53.1, y: 48.6,
    price: "$",
    hours: "Mon–Fri 7:15am–1:45pm; Sat–Sun 8:15am–2:45pm",
  },
  {
    id: "moriwa-matcha",
    name: "Moriwa Matcha",
    address: "1143 Taraval St",
    hood: "Parkside",
    status: "call",
    topPick: false,
    buzzy: true,
    emoji: "🍃",
    note: "Opened in late 2025 on Taraval, with double matcha, fruit matcha, creme brulee, and boba matcha drinks.",
    soyNote: "Soy availability is not listed.",
    source: "https://missionlocal.org/2026/02/sf-sunset-buzz-free-soup/",
    lat: 37.7427951, lng: -122.4786188,
    x: 27.8, y: 62.3,
    price: "$",
    hours: "Mon closed; Tue–Fri 11:30am–5pm; Sat–Sun 11:30am–6:30pm",
  },
  {
    id: "kissakeko",
    name: "Kissakeko",
    address: "1327 Mason St",
    hood: "Nob Hill",
    status: "call",
    topPick: false,
    buzzy: true,
    emoji: "🎧",
    note: "Tiny Japanese jazz-kissa and sake bar with daytime cafe service, matcha, pastries, and mocktails.",
    soyNote: "Soy availability is not listed.",
    source: "https://www.theinfatuation.com/san-francisco/reviews/kissakeko",
    lat: 37.7957579, lng: -122.4119215,
    x: 55.3, y: 33.7,
    price: "$$",
    hours: "Mon, Thu–Sat 1–8pm; closed Sun, Tue, Wed",
  },
  {
    id: "hologram",
    name: "Hologram",
    address: "2512 Clement St",
    hood: "Outer Richmond",
    status: "call",
    topPick: false,
    buzzy: true,
    emoji: "📼",
    note: "Soft-opened Outer Richmond cafe from the Snowbird Coffee/Malama Matcha team, serving Snowbird coffee, Malama matcha, breakfast sandwiches, burritos, and tater tots.",
    soyNote: "Soy availability is not listed.",
    source: "https://www.tablehopper.com/newsletter/this-weeks-tablehopper-looking-up-free/",
    lat: 37.7820837, lng: -122.4862562,
    x: 24.6, y: 41.1,
    price: "$$",
    hours: "Wed–Sun 8am–2pm",
  },
  {
    id: "hanabi-sushi-and-boba",
    name: "Hanabi Sushi & Boba",
    address: "219 King St",
    hood: "Mission Bay",
    status: "call",
    topPick: false,
    buzzy: true,
    emoji: "🍣",
    note: "New Mission Bay sushi-and-boba counter with a dedicated boba drink lineup that includes matcha latte, matcha brown sugar, matcha cloud green tea, matcha strawberry, and matcha Oreo.",
    soyNote: "Soy availability is not listed; the matcha drinks use fresh milk.",
    source: "https://www.ubereats.com/store/hanabi-sushi-%26-boba/1Bf-rJIDVTaaYCOUSBLs7g",
    lat: 37.7778364, lng: -122.3924713,
    x: 63.3, y: 43.4,
    price: "$",
    hours: "Daily 11am–9pm",
  },
  {
    id: "saltwater-bakeshop",
    name: "Saltwater Bakeshop",
    address: "1309 Howard St",
    hood: "SoMa",
    status: "none",
    topPick: false,
    buzzy: true,
    emoji: "🥐",
    note: "Cult-favorite bakery's first cafe soft-opened in SoMa with daily breads, pastries, coffee, and a spring strawberry matcha pound cake with matcha glaze.",
    soyNote: "This location lists a seasonal matcha cake, not a matcha drink; soy milk is not listed.",
    source: "https://www.saltwaterbakeshop.com/",
    lat: 37.774689, lng: -122.413303,
    x: 54.7, y: 45.1,
    price: "$$",
    hours: "Tue–Fri 7am–3pm; Sat–Sun 8am–3pm; closed Mon",
  },
  {
    id: "hardware-coffee-co-west-portal",
    name: "Hardware Coffee Co. - West Portal",
    address: "32 W Portal Ave",
    hood: "West Portal",
    status: "call",
    topPick: false,
    buzzy: true,
    emoji: "🛠️",
    note: "Opened in May 2026 as an all-day cafe and flower shop with espresso drinks, matcha, cold brew, pastries, and lots of seating.",
    soyNote: "Soy availability is not listed for the matcha lattes.",
    source: "https://www.theinfatuation.com/san-francisco/reviews/hardware-coffee-co",
    lat: 37.7405782, lng: -122.4664712,
    x: 32.8, y: 63.5,
    price: "$$",
    hours: "Daily 6am–6pm",
  },
  {
    id: "corgi-cafe",
    name: "Corgi Cafe",
    address: "9 Claude Ln",
    hood: "FiDi / Union Square",
    status: "call",
    topPick: false,
    buzzy: true,
    emoji: "💻",
    note: "New 24/7 cafe and work hub with coffee, tea, protein smoothies, and ceremonial-grade Uji matcha.",
    soyNote: "Soy availability is not listed; other milk alternatives are available.",
    source: "https://www.doordash.com/store/corgi-cafe-san-francisco-40907031/",
    lat: 37.789948, lng: -122.4043475,
    x: 58.5, y: 36.8,
    price: "$$",
    hours: "Open 24 hours",
  },
  {
    id: "roots-and-craft-tea-roasters",
    name: "Roots & Craft Tea Roasters",
    address: "1555 Clement St",
    hood: "Inner Richmond",
    status: "call",
    topPick: false,
    buzzy: true,
    emoji: "🌱",
    note: "Announced 2026 tea-focused cafe from Maya Mori with cup-by-cup Japanese teas, matcha, hojicha, and CHEN&coffee inside.",
    soyNote: "Soy availability is not listed for the planned matcha lattes.",
    source: "https://www.sfgate.com/food/article/sf-richmond-district-cafe-boom-21955411.php/",
    lat: 37.7822997, lng: -122.4761465,
    x: 28.8, y: 40.9,
    price: "$$",
    hours: "Planned for later 2026",
  },
  {
    id: "tokyo-cream",
    name: "Tokyo Cream",
    address: "1838 Irving St",
    hood: "Outer Sunset",
    status: "call",
    topPick: false,
    buzzy: true,
    emoji: "🍦",
    note: "New Japanese dessert cafe with Hokkaido soft serve, matcha drinks, and early local buzz for cream-topped matcha.",
    soyNote: "Soy availability is not listed for the matcha drinks or soft serve.",
    source: "https://www.corner.inc/place/pUdKe9T3iftB",
    lat: 37.7636754, lng: -122.477829,
    x: 28.3, y: 51.1,
    price: "$$",
    hours: "Mon 11am–9pm; Tue closed; Wed–Thu 11am–9pm; Fri 11am–10pm; Sat 10am–10pm; Sun 10am–9pm",
  },
  {
    id: "constance-tea",
    name: "Constance Tea",
    address: "3512 Balboa St",
    hood: "Outer Richmond",
    status: "call",
    topPick: true,
    buzzy: true,
    emoji: "🍵",
    note: "Soft-opened May 31, 2026 as a matcha and tea studio milling Japanese tencha leaves in house on stone mills.",
    soyNote: "Soy availability is not listed for the matcha and tea lattes.",
    source: "https://www.constancetea.com/",
    lat: 37.7758347, lng: -122.4965118,
    x: 20.4, y: 44.5,
    price: "$$",
    hours: "Daily 8am–4pm; closed Tue",
  },
  {
    id: "heytea-downtown",
    name: "HEYTEA - Downtown Metreon",
    address: "165 4th St",
    hood: "SoMa",
    status: "none",
    topPick: false,
    buzzy: true,
    emoji: "🧋",
    note: "SF's first HEYTEA location at the Metreon; known for the Supreme Matcha (matcha latte with matcha cheese foam) and 1000 Mesh Matcha drinks.",
    soyNote: "Soy is not listed; the matcha drinks use dairy milk and dairy-based cheese foam.",
    source: "https://www.yelp.com/biz/heytea-san-francisco",
    lat: 37.7821, lng: -122.4047,
    x: 58.3, y: 41.1,
    price: "$$",
    hours: "Daily 11am–8pm",
  },
  {
    id: "sohn",
    name: "SŌHN",
    address: "2535 3rd St",
    hood: "Dogpatch",
    status: "call",
    topPick: true,
    buzzy: true,
    emoji: "🍚",
    note: "Korean American-inspired all-day cafe in Dogpatch from Chef Deuki Hong; cream-topped matcha latte and banana oat milk matcha are signature drinks.",
    soyNote: "Banana milk and oat milk are available; soy availability is not listed.",
    source: "https://www.sohnsf.com/",
    lat: 37.7597, lng: -122.3876,
    x: 65.3, y: 53.2,
    price: "$$",
    hours: "Wed–Sun 9am–4pm; closed Mon–Tue",
  },
  {
    id: "heytea-stonestown-galleria",
    name: "HEYTEA - Stonestown Galleria",
    address: "3251 20th Ave, Level 1",
    hood: "Stonestown",
    status: "call",
    topPick: false,
    buzzy: true,
    emoji: "🧋",
    note: "Second SF HEYTEA location planned for Level 1 of Stonestown Galleria.",
    soyNote: "Soy availability for the planned Stonestown location is not listed.",
    source: "https://maps.apple.com/place?place-id=IEEA1F36900BEAE7D",
    lat: 37.7277726, lng: -122.4768761,
    x: 28.5, y: 70.5,
    price: "$$",
    hours: "Opening expected summer 2026",
  },
  {
    id: "jandii-cafe-taraval",
    name: "Jandii Cafe",
    address: "1100 Taraval St",
    hood: "Parkside",
    status: "none",
    topPick: true,
    buzzy: true,
    emoji: "🍵",
    note: "From the Sweet Maple/U:Dessert Story owners, with a focused menu of ceremonial-grade Japanese matcha, freshly baked scones, and espresso.",
    soyNote: "Soy is not listed; oat and almond milk are available.",
    source: "https://www.yahoo.com/lifestyle/articles/sweet-maple-owners-open-3-120000794.html",
    lat: 37.743031, lng: -122.477997,
    x: 28.1, y: 62.4,
    price: "$$",
    hours: "Daily 9am–4pm",
  },
  {
    id: "always-awake-coffee",
    name: "Always Awake Coffee",
    address: "611 Post St",
    hood: "Lower Nob Hill",
    status: "call",
    topPick: false,
    buzzy: true,
    emoji: "☕",
    note: "New Korean-aesthetic cafe with a bamboo matcha coffee, strawberry matcha latte, and creative flavored lattes; opened April 2026.",
    soyNote: "Soy availability is not listed for the matcha drinks.",
    source: "https://www.yelp.com/biz/always-awake-coffee-san-francisco",
    lat: 37.7877, lng: -122.4149,
    x: 54.1, y: 38.0,
    price: "$",
    hours: "Mon–Fri 7am–8pm; Sat–Sun 7am–6pm",
  },
  {
    id: "kamari-coffee",
    name: "Kamari Coffee",
    address: "333 Market St",
    hood: "FiDi",
    status: "none",
    topPick: false,
    buzzy: true,
    emoji: "☕",
    note: "Coffee cart turned brick-and-mortar; opened in FiDi around May 2026 and recently added matcha to the menu.",
    soyNote: "Soy is not listed; whole milk and oat milk are available.",
    source: "https://www.kamaricoffee.co/",
    lat: 37.7906, lng: -122.3990,
    x: 60.6, y: 36.5,
    price: "$",
    hours: "Mon–Thu 7am–3:30pm; Fri–Sun closed",
  },
  {
    id: "double-black-sf",
    name: "Double Black SF",
    address: "925 Cole St",
    hood: "Cole Valley",
    status: "none",
    topPick: false,
    buzzy: true,
    emoji: "⛷️",
    note: "Cafe inside the Yardsale outdoor gear shop from former Shark Tank contestants; opened May 2026 with a menu of lattes, matcha, and Saltwater Bakeshop pastries.",
    soyNote: "Soy is not listed; almond and oat milk are available.",
    source: "https://sfstandard.com/2026/01/26/double-black-sf-yardsale-cole-valley/",
    lat: 37.7659, lng: -122.4487,
    x: 40.1, y: 49.8,
    price: "$",
    hours: "hours TBD",
  },
  {
    id: "konbini-sf",
    name: "Konbini SF",
    address: "2790A Harrison St",
    hood: "Mission",
    status: "call",
    topPick: false,
    buzzy: true,
    emoji: "🍙",
    note: "Spring 2026 brick-and-mortar for the former onigiri pop-up, serving onigiri, bento boxes, Asian snacks, and matcha drinks.",
    soyNote: "Soy availability is not listed for the matcha drinks.",
    source: "https://www.theinfatuation.com/san-francisco/guides/new-san-francisco-restaurant-openings",
    lat: 37.7528025, lng: -122.4119871,
    x: 55.3, y: 57.0,
    price: "$",
    hours: "Tue–Thu 10am–2pm; Fri–Sat 10am–4pm",
  },
  {
    id: "binge-coffee-house",
    name: "Binge Coffee House",
    address: "530 Valencia St",
    hood: "Mission",
    status: "none",
    topPick: false,
    buzzy: true,
    emoji: "🧋",
    note: "Berkeley-born Vietnamese coffee, boba, and matcha cafe; SF location on Valencia with a dedicated ceremonial matcha section (Uji, fruit, sesame, ube, banana, and coconut matcha drinks).",
    soyNote: "No soy — oat and almond milk only.",
    source: "https://missionlocal.org/2026/06/make-out-room-owner-says-hes-leaving-the-biz-with-his-liver-intact/",
    lat: 37.7643364, lng: -122.4219025,
    x: 51.2, y: 50.7,
    price: "$",
    hours: "Mon–Thu 9am–6pm; Fri–Sun 9am–8pm",
  },
  {
    id: "telescope-coffee",
    name: "Telescope Coffee",
    address: "345 6th St",
    hood: "SoMa",
    status: "call",
    topPick: false,
    buzzy: true,
    emoji: "🔭",
    note: "POC women-owned cafe recently reopened in a new SoMa space; creative matcha drinks including blueberry matcha latte, orange vanilla matcha, and iced matcha rose latte.",
    soyNote: "Oat and coconut milk are available; soy availability is not listed.",
    source: "https://www.telescopecoffee.com/",
    lat: 37.7786, lng: -122.4064,
    x: 57.6, y: 43.0,
    price: "$",
    hours: "Mon–Fri 7am–4pm; Sat–Sun 7am–3pm",
  },
  {
    id: "reveille-chestnut",
    name: "Réveille Coffee - Chestnut St",
    address: "2268 Chestnut St",
    hood: "Marina",
    status: "reported",
    topPick: false,
    buzzy: false,
    emoji: "☕",
    note: "Marina Réveille location serving a matcha latte.",
    soyNote: "Soy milk is available for other lattes and may be available as a matcha substitution.",
    source: "https://www.cafereveille.com/",
    lat: 37.8006, lng: -122.4376,
    x: 44.7, y: 31.1,
    price: "$",
    hours: "daily 7am–5pm",
  },
  {
    id: "stray-dog",
    name: "Stray Dog",
    address: "2545 24th St",
    hood: "Mission",
    status: "call",
    topPick: false,
    buzzy: true,
    emoji: "☕",
    note: "New cafe-by-day, bar-by-night Mission spot from the Lost Cat owner, serving a Strawberry Matcha Cloud drink.",
    soyNote: "Soy availability is not listed for the matcha drinks.",
    source: "https://maps.roadtrippers.com/us/san-francisco-ca/food-drink/stray-dog-san-francisco-ca--0",
    lat: 37.7530372, lng: -122.4047986,
    x: 58.2, y: 56.8,
    price: "$$",
    hours: "Cafe daily 8am–3pm; bar Mon–Thu 5–10pm, Fri–Sat 5pm–midnight",
  },
  {
    id: "oklava-cafe-saluhall",
    name: "Oklava Cafe - Saluhall",
    address: "945 Market St Ste 102",
    hood: "SoMa / Mid-Market",
    status: "call",
    topPick: false,
    buzzy: true,
    emoji: "☕",
    note: "New Saluhall Turkish bakery/cafe from the Palo Alto Oklava team, serving an iced matcha latte alongside coffee, breakfast, bowls, and pastries.",
    soyNote: "Soy availability is not listed for the iced matcha latte.",
    source: "https://postmates.com/store/oklava-cafe-saluhall/MIm3Z7A2VIydCJmtDLQpOw?diningMode=DELIVERY",
    lat: 37.7829036, lng: -122.4092662,
    x: 56.4, y: 40.7,
    price: "$$",
    hours: "Daily 11:30am–6:30pm",
  },
];

const STATUS_META = {
  confirmed: { label: "soy confirmed", color: "#8FBF3F", ink: "#1a3a1a", short: "soy ✓" },
  reported: { label: "soy reported", color: "#FFB84D", ink: "#5a3a00", short: "soy ?" },
  none:     { label: "no soy listed", color: "#E5E0D5", ink: "#3a3a3a", short: "no soy" },
  call:     { label: "soy TBD", color: "#7FC4FF", ink: "#0a3a5a", short: "soy TBD" },
  closed:   { label: "temp closed", color: "#FF7A8A", ink: "#5a0a1a", short: "closed" },
};

window.SHOPS = SHOPS;
window.STATUS_META = STATUS_META;
